# Site settings
title: ajbeach2.github.io
email: your-email@yourdomain.com
description: "A blog about the things that github.com/ajbeach2"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: abeach4life
github_username:  ajbeach2
linkedin_username:  ajbeach2

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]