# Site settings
title: ajbeach2.github.io
description: > # this means to ignore newlines until "baseurl:"
  A development blog amoung other things
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://ajbeach2.github.io # the base hostname & protocol for your site
github:  https://github.com/ajbeach2
linkedin: https://www.linkedin.com/in/ajbeach2
google_plus: https://plus.google.com/u/0/110964463944333047729
markdown: kramdown
